# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-19 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myInstagram', '0002_auto_20201019_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_url',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
