# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-19 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myInstagram', '0004_auto_20201019_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='profile',
        ),
    ]
