# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-19 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myInstagram', '0006_auto_20201019_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='comments',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=130),
        ),
    ]
